backend:
  name: github
  repo: danganhuh/tum-web-lab2
  branch: master

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "site_content"
    label: "Site Content"
    folder: "src/content/site"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
